[package]
name = "PROJECT_NAME-sys"
version = "MAJOR_VERSION.MINOR_VERSION.PATCH_VERSION"
description="test package"
license="BSD-3-Clause"
authors = ["Anders Langlands <anderslanglands@gmail.com>"]
edition = "2018"
exclude = [
]

[build-dependencies]
cppmm-build = "^0.3"
